@startuml 図7-10

|客|
|客|
|定員|
|定員|

|客|
start
:弁当をレジに持っていく;
|客|
|定員|
fork
|定員|
    |客|
    :弁当をレジに持っていく;
    |客|
|定員|
:清算する;
fork again
if (温めますか?) then (Yes)
    :弁当を温める;
else (No)
endif
:弁当を袋に入れる;
|定員|
end fork
|客|
:弁当を手にもつ;
|客|
stop
@enduml
