@startuml 演習3-4
left to right direction
object "<u>車情報: 車</u>" as car {
メーカー:"トヨタ"
車種:"プリウス"
色:"赤"
車両番号:"JTDKN3DU5D1612345"
}
object "<u>タイヤ1: タイヤ</u>" as t1 {
メーカー:"ブリヂストン"
サイズ:"205/60R16"
}
object "<u>タイヤ2: タイヤ</u>" as t2 {
メーカー:"ブリヂストン"
サイズ:"205/60R16"
}
object "<u>タイヤ3: タイヤ</u>" as t3 {
メーカー:"ブリヂストン"
サイズ:"205/60R16"
}
object "<u>タイヤ4: タイヤ</u>" as t4 {
メーカー:"ブリヂストン"
サイズ:"205/60R16"
}
car -- t1
car -- t2
car -- t3
car -- t4
@enduml