@startuml 演習7-4-1
left to right direction
skinparam classAttributeIconSize 0
class 注文 {
合計
}
class 注文明細 {
数量
小計
}
class 割引クーポン {
値引き額
期限
}
class 商品 {
名称
単価
}
class ドリンク {
種別
}
class カップ {
サイズ
}
class レシピ {

}
class フード {

}
class ポテト {
サイズ
}
class ハンバーガー {
種別
}
class 材料 {

}

注文 "1..*" o-- 注文明細
注文明細 "0..*" -right- 商品
注文明細 "0..1" -- 割引クーポン
ドリンク --|> 商品
フード -left-|> 商品
カップ "0..*" -- ドリンク
フード "1" -- "1" レシピ
ポテト -up-|> フード
ハンバーガー -left-|> フード
材料 "1..*" --o ハンバーガー
パン --|> 材料
肉 --|> 材料
野菜 --|> 材料
チーズ --|> 材料
@enduml